name: persotant
description: The simple personal accountancy application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.3.0
  get_it: ^7.6.0
  dartz: ^0.10.1
  provider: ^6.0.5
  internet_connection_checker: ^1.0.0+1
  pinput: ^2.3.0
  hive: ^2.2.3
  path_provider: ^2.0.15
  equatable: ^2.0.5
  rxdart: ^0.27.7
  queue: ^3.1.0+2
  device_info_plus: ^9.0.2
  permission_handler: ^10.4.3
  path: ^1.8.3
  flutter_secure_storage: ^8.0.0
  introduction_screen: ^3.1.11
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/slider/
  #   - images/a_dot_ham.jpeg
  # example:
  fonts:
    - family: Vazir
      fonts:
        - asset: assets/fonts/vazir/Vazirmatn-RD-FD-Black.ttf
        - asset: assets/fonts/vazir/Vazirmatn-RD-FD-Bold.ttf
        - asset: assets/fonts/vazir/Vazirmatn-RD-FD-ExtraBold.ttf
        - asset: assets/fonts/vazir/Vazirmatn-RD-FD-ExtraLight.ttf
        - asset: assets/fonts/vazir/Vazirmatn-RD-FD-Light.ttf
        - asset: assets/fonts/vazir/Vazirmatn-RD-FD-Medium.ttf
        - asset: assets/fonts/vazir/Vazirmatn-RD-FD-Regular.ttf
        - asset: assets/fonts/vazir/Vazirmatn-RD-FD-SemiBold.ttf
        - asset: assets/fonts/vazir/Vazirmatn-RD-FD-Thin.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
